### ISSUE TITLE
UI inconsistencies in the logout dialog box

### ISSUE THREAD

**Issue by laxyapahuja** [openMF/mifos-mobile-cn#111] opened 2020-01-06 16:06 UTC
## Summary

There are UI inconsistencies in the dialog box when logging out.

## Steps to reproduce

Login -> Drawer -> Logout

## Expected behaviour

The app should show a dialog box with proper margins and it should follow the Material guidelines.

## Observed behaviour

A dialog box appears which has an inconsistent UI and does not follow the Material guidelines.

## Device and Android Version

Android 9, Mi A3

## Screenshots

<img src="https://user-images.githubusercontent.com/31318248/71830327-86b9b300-30cc-11ea-8d84-e12dafe26bb2.png" width=300/>

**Comment by rachittt** [comment] 2020-01-06 18:43
@laxyapahuja this issue cannot be reproduced by others simply because you have changed the `AppTheme` in the `styles.xml` from `Theme.AppCompat.Light.NoActionBar` to `Theme.MaterialComponents.Light.NoActionBar` in your local branch. Unless #110 gets merged, this issue does not make sense.

**Comment by laxyapahuja** [comment] 2020-01-06 18:49
> @laxyapahuja this issue cannot be reproduced by others simply because you have changed the `AppTheme` in the `styles.xml` from `Theme.AppCompat.Light.NoActionBar` to `Theme.MaterialComponents.Light.NoActionBar` in your local branch. Unless #110 gets merged, this issue does not make sense.

Thank you for pointing that out. However, I won't take this issue down because the redesign requires us to add Material AppTheme in the project. So, it's going to occur in the future. It's better if we make the app compatible to the Material theme :)

**Comment by ashwinkey04** [comment] 2020-01-13 11:44
I think it will be a good idea if this PR is tagged 'later'

**Comment by ashwinkey04** [comment] 2020-01-13 11:53
I think it will be a good idea if this PR is labelled 'later'

**Comment by rachittt** [comment] 2020-01-25 13:47
@laxyapahuja, now that #122 has been merged, this issue is reproducible.

**Comment by laxyapahuja** [comment] 2020-01-27 16:06
@luckyman20 can be closed now.

**Closed** 2020-01-27 16:25 UTC
